package com.karas.wftoolkit.DBFlow;

import java.util.HashMap;

/**
 * Created by Hongliang Luo on 2019/7/5.
 **/
public final class TranslateMap {
    private static HashMap<String,String>stringHashMap=new HashMap<>();

    public static HashMap<String, String> getStringHashMap() {
        return stringHashMap;
    }

    public static void clearMap(){
        stringHashMap.clear();
    }
    
    private static void put(String key,String value){
        stringHashMap.put(key.toLowerCase(),value);
    }
    //key:en  value:cn
    public static void mapPreInstall(){
        put("to","到");
        put("leave","离开");
        put("come","到来");
        put("cetus","希图斯");
        put("day","白昼");
        put("night","夜晚");
        put("warm","温暖");
        put("cold","寒冷");
        put("earth","地球");
        put("orb vallis","奥布山谷");
        put("fomorian","巨人战舰");
        put("razorback","利刃豺狼");
        put("detonite injector","爆燃喷射器");
        put("fieldron","电磁力场装置");
        put("3 detonite injector","3X爆燃喷射器");
        put("3 fieldron","3X电磁力场装置");
        put("mutalist alad v nav coordinate","异融AV导航坐标");
        put("mutagen mass","突变原聚合物");
        put("2 mutagen mass","2X突变原聚合物");
        put("orokin catalyst","Orokin催化剂");
        put("orokin reactor","Orokin反应堆");
        put("Bp","蓝图");
        put("blueprint","蓝图");
        put("exilus adapter","特殊功能槽连接器");
        put("karak","卡拉克");
        put("latron","拉特昂");
        put("wraith","亡魂");
        put("strun","斯特朗");
        put("twin","双子");
        put("vipers","蝰蛇");
        put("sheev","希芙");
        put("dera","德拉");
        put("vandal","破坏者");
        put("snipetron","狙击特昂");
        put("defense","防御");
        put("mobile","移动");
        put("assassina","刺杀");
        put("assassination","刺杀");
        put("capture","捕获");
        put("defection","叛逃");
        put("excavation","挖掘");
        put("extermination","歼灭");
        put("hijack","劫持");
        put("interception","拦截");
        put("rescue","救援");
        put("spy","间谍");
        put("sabotage","破坏");
        put("survival","生存");
        put("crossfire","多方交战");
        put("jupiter","木星");
        put("void","虚空");
        put("mercury","水星");
        put("venus","金星");
        put("lua","月球");
        put("mars","火星");
        put("phobos","火卫一");
        put("ceres","谷神星");
        put("europa","欧罗巴");
        put("saturn","土星");
        put("uranus","天王星");
        put("neptune","海王星");
        put("pluto","冥王星");
        put("sedna","赛德娜");
        put("kuva","赤毒");
        put("fortress","要塞");
        put("eris","阋神星");
        put("derelict","被遗弃的Orokin船只");
        put("solaris United","索拉里斯联盟");
//        put("Ostrons","");
        put("lith","古纪");
        put("meso","前纪");
        put("neo","中纪");
        put("axi","后纪");
        put("barrel","枪管");
        put("receiver","枪机");
        put("link","连接器");
        put("stock","枪托");
        put("blade","刀刃");
        put("heatsink","散热片");
        put("hilt","握柄");
        put("grip","弓身");
        put("limb","弓臂");
        put("upper","上");
        put("lower","下");
        put("string","弓弦");
        put("enemy","敌人");
        put("elemental","元素");
        put("enhancement","强化");
        put("enhanced","强化");
        put("blast","爆炸");
        put("corrosive","腐蚀");
        put("electricity","电击");
        put("gas","毒气");
        put("heat","火焰");
        put("magnetic","磁力");
        put("radiation","辐射");
        put("toxin","毒素");
        put("viral","病毒");
        put("physical","物理");
        put("impact","冲击");
        put("puncture","穿刺");
        put("slash","切割");
        put("enhanced enemy shields","敌人护盾强化");
        put("enhanced enemy armor","敌人护甲强化");
        put("cryogenic leakage","冷却液泄露");
        put("dense fog","浓雾");
        put("electromagnetic anomalies","电磁异常");
        put("energy reduction","能量上限减少");
        put("eximus stronghold","卓越者大本营");
        put("extreme cold","极度寒冷");
        put("fire","火灾");
        put("low gravity","低重力");
        put("radiation hazard","辐射灾害");
        put("Environmental Hazard","环境灾害");
        put("Environmental","环境");
        put("Hazard","灾害");
        put("Pockets","区域");//especially
        put("rifle","步枪");
        put("assault","突击");
        put("melee","近战");
        put("secondary","副武器");
        put("shotgun","霰弹枪");
        put("sniper","狙击枪");
        put("bow","弓箭");
        put("only","限定");
        put("weapon","武器");
        put("restriction","限制");
        put("kill thumper","击杀巨牙重击者公牛");
        put("hard kill thumper","击杀巨牙重击者朵玛");
        put("complete venus race","完成金星滑板比赛");
        put("accelerator","加速者");
        put("kill 20 enemies while sliding","滑行中击杀20名敌人");
        put("agent","特务");
        put("complete a mission","完成1项任务");
        put("arsonist","纵火犯");
        put("kill 150 enemies with heat damage","使用火焰伤害击杀150名敌人");
        put("attractive","吸引力");
        put("kill 150 enemies with magnetic damage","使用磁力伤害击杀150名敌人");
        put("biohazard","生化危害");
        put("kill 150 enemies with gas damage","使用毒气伤害击杀150名敌人");
        put("communicator","交流者");
        put("mark 5 mods or resources","标记5个Mod或资源");
        put("deep freeze","极度冰冻");
        put("kill 150 enemies with cold damage","使用冰冻伤害击杀150名敌人");
        put("detonator","引爆者");
        put("kill 150 enemies with blast damage","使用爆炸伤害击杀150名敌人");
        put("energizing","能量提升");
        put("pick up 20 energy orbs","拾取20个能量球");
        put("everything old is new again","以旧换新");
        put("complete 3 transmutations","完成3次转换");
        put("executioner","处刑者");
        put("kill 10 enemies with finishers","使用终结攻击击杀10名敌人");
        put("expressive","善于表达");
        put("play 1 emote","使用一个表情动作");
        put("glider","滑翔者");
        put("kill 10 enemies while aim gliding","飞身瞄准时击杀20名敌人");
        put("graffiti","涂鸦");
        put("deploy a glyph","设置一枚浮印");
        put("deploy a glyph WHILE IN A MISSION","在任务中设置一枚浮印");
        put("deploy air support","部署空中支援");
        put("hacker","黑客");
        put("hack 8 terminals","骇入8个控制台");
        put("kleptomaniac","盗窃癖");
        put("open 20 lockers","打开20个储藏箱");
        put("loyalty","忠诚不二");
        put("interact with your kubrow or kavat","和库伯或库娃进行互动");
        put("marksman","老练射手");
        put("kill 40 enemies with headshots","爆头击杀40名敌人");
        put("Meltdown","熔毁");
        put("kill 150 enemies with corrosive damage","使用腐蚀伤害击杀150名敌人");
        put("mow them down","撂倒他们");
        put("kill 150 enemies with a primary weapon","使用主要武器击杀150名敌人");
        put("poisoner","投毒者");
        put("kill 150 enemies with toxin damage","使用毒素伤害击杀150名敌人");
        put("power trip","力量展现");
        put("kill 150 enemies with abilities","使用技能击杀150名敌人");
        put("reactor","核反应");
        put("kill 150 enemies with radiation damage","使用辐射伤害击杀150名敌人");
        put("researcher","研究者");
        put("scan 25 objects or enemies","扫描25次对象或敌人");
        put("saver","储蓄者");
        put("pick up 15,000 credits","拾取15,000现金");
        put("sharing is caring","有毒共享");
        put("kill 150 enemies with viral damage","使用病毒伤害击杀150名敌人");
        put("shiny","闪闪发亮");
        put("pick up 8 mods","拾取8个Mod");
        put("short circuit","短路");
        put("kill 150 enemies with electricity damage","使用电击伤害击杀150名敌人");
        put("smaller is bigger","小兵大功");
        put("kill 150 enemies with a secondary weapon","使用次要武器击杀150名敌人");
        put("sword dance","剑舞");
        put("kill 150 enemies with a melee weapon","使用近战武器击杀150名敌人");
        put("trampoline","蹦弹");
        put("bullet jump 150 times","旋身飞跃150次");
        put("warning shot","开枪警告");
        put("kill 200 enemies","击杀200名敌人");
        put("animator","动像者");
        put("fully socket 3 ayatan sculptures","完整插满3座阿耶檀识塑像");
        put("assassin","刺客");
        put("complete 3 assassination missions","完成3项刺杀任务");
        put("cache hunter","箱子猎人");
        put("find all caches in 3 sabotage missions","在3项破坏任务中找到所有储藏箱");
        put("conservationist","保育者");
        put("complete 6 different perfect animal captures","完成6个完美的动物捕获");
        put("don't blow it","别搞砸了");
        put("complete 12 conduits in disruption","中断任务完成12个导管");
        put("Earth Bounty Hunter","地球赏金猎人");
        put("Complete 5 different Bounties in the Plains of Eidolon","在夜灵平野完成5项不同的赏金任务");
        put("Earth Fisher","地球渔者");
        put("Catch 6 Rare Fish in the Plains of Eidolon","在夜灵平野捕获6条稀有鱼");
        put("Earth Miner","地球矿工");
        put("Mine 6 Rare Gems or Ore in the Plains of Eidolon","在夜灵平野挖到6个稀有宝石或矿石");
        put("Mine 6 Rare Gems in the Plains of Eidolon","在夜灵平野挖到6个稀有宝石");
        put("Eliminator","排除者");
        put("Complete 3 Exterminate missions","完成3项歼灭任务");
        put("Enhance!","增强");
        put("Pick up 8 Rare Mods","拾取8个稀有Mod");
        put("Eximus Eliminator","卓越处刑者");
        put("Kill 30 Eximus","击杀30名卓越者");
        put("Gilded","镀金");
        put("Gild 1 Modular Items","镀金一个模块物品");
        put("Good Friend","好朋友");
        put("Help Clem with his weekly mission","帮助Clem完成它的周常任务");
        put("Invader","入侵者");
        put("Complete 9 Invasion missions of any type","完成9项任何类型的入侵任务");
        put("Jailer","狱吏");
        put("Complete 3 Capture missions","完成3项捕获任务");
        put("Not a Warning Shot","这不是警告射击");
        put("Kill 500 Enemies","击杀500名敌人");
        put("Operative","特工");
        put("Complete 3 Spy missions","完成3项间谍任务");
        put("Polarized","极化");
        put("Polarize with Forma 3 times (not in Simulacrum)","使用3次Forma完成极化");
        put("Protector","保护者");
        put("Complete 3 Mobile Defense missions","完成3次移动防御任务");
        put("Rescuer","救援者");
        put("Complete 3 Rescue missions","完成3项救援任务");
        put("Saboteur","破坏者");
        put("Complete 3 Sabotage missions","完成3次破坏任务");
        put("Sanctuary Researcher","圣殿研究员");
        put("Complete 5 Scans for Cephalon Simaris","完成5个中枢Simaris扫描");
        put("Sound Sleeper","声之眠者");
        put("Complete 3 Nightmare missions of any type","完成3项任意类型噩梦任务");
        put("Sortie Specialist","突击专家");
        put("Complete 1 Sortie","完成一项突击任务");
        put("Complete 1 Sorties","完成一项突击任务");
        put("Supporter","支持者");
        put("Complete 10 Syndicate missions","完成10项集团任务");
        put("Test Subject","测试者");
        put("Complete 3 waves of Sanctuary Onslaught","完成3波圣殿突袭");
        put("Unlock Relics","解开遗物");
        put("Unlock 3 Relics","解开3个虚空遗物");
        put("Vault Looter","宝库劫者");
        put("Unlock 4 Orokin Derelict Vaults","解锁4个Orokin宝库");
        put("Venus Bounty Hunter","金星赏金猎人");
        put("Complete 5 different bounties in the Orb Vallis","在奥布山谷完成5项不同的赏金任务");
        put("Complete 8 bounties in the Orb Vallis","在奥布山谷完成8项不同的赏金任务");
        put("Venus Fisher","进行渔者");
        put("Catch 6 Rare Servofish in the Orb Vallis","在奥布山谷捕获6条稀有伺服鱼");
        put("Venus Miner","金星矿工");
        put("Mine 6 Rare Gems or Ore in the Orb Vallis","在奥布山谷挖到6个稀有宝石或矿石");
        put("Mine 6 Rare Gems in the Orb Vallis","在奥布山谷挖到6个稀有宝石");
        put("Ascendant","上行");
        put("Complete 4 Halls of Ascension on Lua","完成月球上的4间晋升大厅");
        put("Day Trader","日间商人");
        put("Win 3 wagers in a row without letting the enemy score in one match of The Index.","在指数之场一场3注中没有让敌人得分");
        put("Complete a Defense mission reaching at least wave 20","完成至少20波防御");
        put("Elite Test Subject","精英测试主题");
        put("Complete 8 Zones of Elite Sanctuary Onslaught","在精英圣殿突袭中完成区域8");
        put("Eximus Executioner","卓越处刑者");
        put("Kill 100 Eximus","击杀100个卓越者");
        put("Grove Guardian","树庭守护者");
        put("Kill 3 Silver Grove Specters","击杀3名落银树庭魅影");
        put("Hold Your Breath","屏住呼吸");
        put("Survive over 30 minutes in Kuva Survival","在赤毒生存任务中生存超过30分钟");
        put("Hydrolyst Hunter","水力使猎人");
        put("Kill or Capture an Eidolon Hydrolyst","击杀或捕获一个夜灵水力使");
        put("Kill Shot","杀戮");
        put("Kill 1,500 Enemies","击杀1,500名敌人");
        put("Night Terror","夜晚恐怖");
        put("Complete 10 Nightmare missions of any type","完成10项任意类型的噩梦任务");
        put("Silent Eliminator","寂静歼灭");
        put("Complete an Extermination mission with level 30 or higher enemies without being detected","完成一场30级或更高等级的歼灭任务并且没有被发觉到");
        put("Sortie Expert","突击行家");
        put("Complete 3 Sorties","完成3项突击任务");
        put("Complete a Survival mission reaching at least 30 minutes","完成一场至少30分钟的生存任务");
        put("Unlock 10 Relics","解锁10个虚空遗物");
        put("Transmute Mods","转换Mod");
        put("Interact With Pet","与宠物互动");
        put("Complete Disruption Conduits","完成中断导管");
        put("Use Forma 3 times","使用3次Forma");
        put("Complete 10 Syndicate misions","完成10项集团任务");
        put("Complete 3 waves of Elite Sanctuary Onslaught","完成3波精英圣殿突袭");
//        put("","");
        put("ghoul purge","尸鬼净化");
        put("thermia fractures","热美亚裂缝");
        put("relay station tenno con","中继站Tenno议会");
        put("plague star","瘟疫之星");
        put("Credit","现金");
        put("relic","遗物");
        put("Credits","现金");
        put("Cache","匣");
        put("Endo","内融核心");
        put("Redirection","蓄能重划");
        put("Iradite","伊莱体");
        put("Oxium","奥席金属");
        put("Pressure Point","压迫点");
        put("Cryotic","永冻晶矿");
        put("Grokdrul","葛克度");
        put("Vitality","生命力");
        put("Nistlepod","尼蒐荚");
        put("Plastids","生物质");
        put("Chassis","机体");
        put("Point Blank","抵近射击");
        put("Streamline","简化");
        put("Hornet Strike","黄蜂蛰刺");
        put("Stretch","延伸");
        put("Intensify","聚精会神");
        put("Morphics","非晶态合金");
        put("Gallium","镓");
        put("Steel Fiber","钢铁纤维");
        put("Energy Inversion","能量转化");
        put("Circuits","电路");
        put("Systems","系统");
        put("Burning Wasp","炽热黄蜂");
        put("Reaping Spiral","收割螺旋");
        put("Speed Trigger","灵敏扳机");
        put("Point strike","致命一击");
        put("Enhanced Durability","耐久强化");
        put("Grim Fury","冷面狂怒");
        put("Charged Chamber","蓄力装填");
        put("Control","控制");
        put("Module","模块");
        put("Neural","神经");
        put("Sensors","传感器");
        put("Cell","电池");
        put("Wisp","幽魂");
        put("Gladiator","角斗士");
        put("Aegis","圣盾");
        put("Lens","晶体");
        put("Vigilante","私法");
        put("Armaments","军备");
        put("Augur","预言");
        put("Pact","契约");
        put("Neuroptics","头部神经光元");
        put("Accord","协约");
        put("Might","威猛");
        put("Fervor","热诚");
        put("Supplies","补给");
        put("Seeker","探求");
        put("vice","钳制");
        put("Rush","猛突");
        put("Vigor","活力");
        put("Message","启示");
        put("Reach","通灵");
        put("Resolve","决心");
        put("Pursuit","追踪");
        put("Offense","侵犯");
        put("Secrets","神密");
        put("Finesse","灵巧");
        put("5X Breath Of The Eidolon","5X夜灵之息");
        put("Furax","弗拉克斯");
        put("left","左");
        put("right","右");
        put("Gauntlet","拳套");
        put("Carving Mantis","雕斩螳螂");
        put("Eidolon","夜灵");
        put("Swooping Falcon","猎鹰俯击");
        put("Twirling Spire","回转尖峰");
        put("Mytocardia","心肌菌");
        put("Spore","孢子");
        put("Spores","孢子");
        put("Training","培训");
        put("Debt-Bond","债务券");
        put("Thermal","热能");
        put("Sludge","软泥");
        put("Gorgaricus","葛嘉里菌");
        put("Tepa","提帕");
        put("Nodule","瘤");
        put("Shelter","庇护");
        put("Nano","纳米");
        put("Synth","合成");
        put("Charge","充能");
        put("Overdrive","超载");
        put("Mecha","机甲");
        put("Tek","技法");
        put("Tek Assault","技法猛袭");
        put("Medical","医疗");
        put("Rubedo","红化结晶");
        put("Deconstruct","解构");
        put("Recharge","充能");
        put("Enhance","强化");
        put("Tellurium","碲");
        put("Fiber","纤维");
        put("Empowered","强化");
        put("Gravity","引力");
        put("Advances","预支");
        put("Detonite","爆燃");
        put("Injector","喷射器");
        put("Mutagen","突变原");
        put("Mass","聚合物");
        put("Familial","家族");
        put("Neurodes","神经元");
        put("Reflex","反射");
        put("Pulse","脉冲");
        put("Collateral","连带");
        put("balor","巴罗尔");
        put("tac alert water fight","三伏天");
        put("free roam","自由漫步");
        put("pattern","模式");
        put("mismatch","不匹配");
        put("results","结果");
        put("inaccurate","不准确");
        put("","");
        put("","");
    }
}
